theme: minima
description: A webpage for a UMD affiliated researcher who focuses on leveraging data analysis, mathematical modeling, and open-source research into outcome-oriented public policy solutions.

# Site wide configuration
title: Tyler A. Clark
locale: en_US

header_pages:
  - index.md
  - cv.md
  - publications.md
  - honors.md
  - coursework.md