theme: minima
description: A webpage for a UMD affiliated researcher who focuses on leveraging statistical inference, machine learning, and data analysis into outcome-oriented public policy and business solutions.

# Site wide configuration
title: Tyler A. Clark
locale: en_US

header_pages:
  - index.md
  - publications.md
  - research.md
  - projects.md
  - honors.md
  - coursework.md
  - aboutme.md